apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: helloworld
spec:
  interval: 1m
  url: https://helm-hello-world.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld
spec:
  interval: 5m
  chart:
    spec:
      chart: helloworld
      version: "0.0.2"
      sourceRef:
        kind: HelmRepository
        name: helloworld
      interval: 1m
